/**
 * SQLite connection singleton for the puzzle API.
 *
 * Three physical files (the runtime picks one of the puzzle files):
 *   data/puzzles.sqlite        — full Lichess dataset (~3.6 GB). Used in
 *                                 local dev. Gitignored, regenerated by
 *                                 the import script.
 *   data/puzzles-prod.sqlite   — sampled subset (~80 MB) committed to git
 *                                 and bundled into Netlify Functions.
 *                                 Built by scripts/build-puzzles-prod.ts.
 *   data/progress.sqlite       — *my* attempt log. Survives re-imports.
 *
 * File selection (first match wins):
 *   1. PUZZLES_DB_PATH env override (escape hatch for tests).
 *   2. data/puzzles.sqlite if present (local dev — full dataset).
 *   3. data/puzzles-prod.sqlite (production — committed subset).
 *
 * The chosen file is opened as the main connection and `progress.sqlite`
 * is ATTACHed as `progress`. Cross-file joins work naturally:
 *
 *   SELECT p.*, a.solved
 *   FROM puzzles p
 *   LEFT JOIN progress.attempts a ON a.puzzle_id = p.puzzle_id;
 */
import Database from "better-sqlite3";
import { existsSync } from "node:fs";
import { join } from "node:path";

const DATA_DIR = join(process.cwd(), "data");
const FULL_PUZZLES_PATH = join(DATA_DIR, "puzzles.sqlite");
const PROD_PUZZLES_PATH = join(DATA_DIR, "puzzles-prod.sqlite");
const PROGRESS_DB_PATH = join(DATA_DIR, "progress.sqlite");

function resolvePuzzlesDbPath(): string | null {
  const override = process.env.PUZZLES_DB_PATH?.trim();
  if (override) return existsSync(override) ? override : null;
  if (existsSync(FULL_PUZZLES_PATH)) return FULL_PUZZLES_PATH;
  if (existsSync(PROD_PUZZLES_PATH)) return PROD_PUZZLES_PATH;
  return null;
}

const PUZZLES_DB_PATH = resolvePuzzlesDbPath() ?? FULL_PUZZLES_PATH;

let _db: Database.Database | null = null;

export class PuzzleDbMissingError extends Error {
  constructor() {
    super(
      `Puzzle database not found. Looked for: ${FULL_PUZZLES_PATH} (full) ` +
        `and ${PROD_PUZZLES_PATH} (subset). ` +
        `Run 'npm run data:setup' to import the full Lichess dataset, or ` +
        `'npx tsx scripts/build-puzzles-prod.ts' to build the subset from it.`,
    );
    this.name = "PuzzleDbMissingError";
  }
}

export function getDb(): Database.Database {
  if (_db) return _db;

  const path = resolvePuzzlesDbPath();
  if (!path) {
    throw new PuzzleDbMissingError();
  }

  // Open the puzzles file as the main connection. We could open it readonly
  // for safety, but ANALYZE / pragmas need a writable handle, and there's
  // no real footgun here — the import script blows the file away anyway.
  const db = new Database(path);
  db.pragma("journal_mode = WAL");
  db.pragma("synchronous = NORMAL");
  // 256 MB page cache is plenty for the read-mostly hot set.
  db.pragma("cache_size = -262144");

  // ATTACH the progress file. SQLite creates it automatically if missing.
  // Path is escaped defensively (single quotes in cwd are very unlikely).
  const escaped = PROGRESS_DB_PATH.replace(/'/g, "''");
  db.exec(`ATTACH DATABASE '${escaped}' AS progress`);

  // First-time bootstrap of the progress schema. CREATE INDEX takes a
  // schema-qualified *index* name but an unqualified table name (SQLite
  // resolves the table through the attach search path).
  //
  // `attempts` was added in pass 4. `game_puzzles` was added in pass 6 —
  // CREATE TABLE IF NOT EXISTS keeps existing progress files backwards
  // compatible without a migration framework (single-user app).
  db.exec(`
    CREATE TABLE IF NOT EXISTS progress.attempts (
      id           INTEGER PRIMARY KEY AUTOINCREMENT,
      puzzle_id    TEXT    NOT NULL,
      attempted_at INTEGER NOT NULL,            -- unix epoch ms
      solved       INTEGER NOT NULL CHECK (solved IN (0, 1)),
      hints_used   INTEGER NOT NULL DEFAULT 0,
      duration_ms  INTEGER NOT NULL DEFAULT 0
    );
    CREATE INDEX IF NOT EXISTS progress.idx_attempts_puzzle ON attempts(puzzle_id);
    CREATE INDEX IF NOT EXISTS progress.idx_attempts_at     ON attempts(attempted_at DESC);

    -- Puzzles extracted from my own analysed games. Stored separately from
    -- the Lichess dataset (puzzles.sqlite is regenerated by the import
    -- script; this table must survive that). Synthetic IDs follow
    -- gp_HEX12_PLY so they cannot collide with Lichess 5-char base62
    -- ids; the route layer sniffs the gp_ prefix to pick the right table.
    CREATE TABLE IF NOT EXISTS progress.game_puzzles (
      id              TEXT PRIMARY KEY,                                       -- gp_<12hex>_<ply>
      game_id         TEXT NOT NULL,                                          -- 12-hex sha256(pgn) prefix
      ply             INTEGER NOT NULL,                                       -- halfmove index of the bad move (1-based)
      fullmove        INTEGER NOT NULL,                                       -- chess move number (1, 2, …)
      side            TEXT NOT NULL CHECK (side IN ('w','b')),                -- side to move at the puzzle position
      fen             TEXT NOT NULL,                                          -- position BEFORE the bad move
      solution_moves  TEXT NOT NULL,                                          -- engine PV, space-joined UCI
      played_uci      TEXT,                                                   -- what the user played in the original game
      classification  TEXT NOT NULL CHECK (classification IN ('mistake','blunder')),
      eval_before_cp  INTEGER,                                                -- centipawns at the position before the bad move (NULL for mate)
      eval_after_cp   INTEGER,
      swing_cp        INTEGER NOT NULL,                                       -- abs(eval_before − eval_after); used as a "rating" proxy
      source_url      TEXT,                                                   -- chess.com / lichess game URL if known
      white_name      TEXT,
      black_name      TEXT,
      themes          TEXT NOT NULL,                                          -- space-joined ('blunder from-my-games' …)
      created_at      INTEGER NOT NULL                                        -- unix ms
    );
    CREATE INDEX IF NOT EXISTS progress.idx_gp_game           ON game_puzzles(game_id);
    CREATE INDEX IF NOT EXISTS progress.idx_gp_created        ON game_puzzles(created_at DESC);
    CREATE INDEX IF NOT EXISTS progress.idx_gp_classification ON game_puzzles(classification);
  `);

  _db = db;
  return db;
}

/** Paths used by tooling / status pages. `puzzles` is the file the runtime
 *  will open at next getDb() call (depends on which files exist). */
export const DB_PATHS = {
  puzzles: PUZZLES_DB_PATH,
  puzzlesFull: FULL_PUZZLES_PATH,
  puzzlesProd: PROD_PUZZLES_PATH,
  progress: PROGRESS_DB_PATH,
} as const;
