/** Tailwind utility string for scraped BBC article HTML (no React deps). */
export const FOOTBALL_READ_BODY_CLASS = [
  "football-read-content not-prose w-full max-w-none",
  "text-[17px] font-normal leading-7 text-zinc-700 dark:text-zinc-300",
  "[&_p]:mb-6 [&_p]:mt-0 [&_p+p]:mt-0",
  "[&_p:has(>strong:only-child)]:mb-3 [&_p:has(>strong:only-child)]:mt-10 [&_p:has(>strong:only-child):first-child]:mt-0",
  "[&_p:has(>strong:only-child)>strong]:text-[1.05rem] [&_p:has(>strong:only-child)>strong]:font-bold [&_p:has(>strong:only-child)>strong]:tracking-tight [&_p:has(>strong:only-child)>strong]:text-zinc-900 dark:[&_p:has(>strong:only-child)>strong]:text-zinc-50",
  "[&_h2]:mb-4 [&_h2]:mt-12 [&_h2]:scroll-mt-24 [&_h2]:border-b [&_h2]:border-zinc-200/90 [&_h2]:pb-3 [&_h2]:font-serif [&_h2]:text-xl [&_h2]:font-bold [&_h2]:tracking-tight [&_h2]:text-zinc-900 dark:[&_h2]:border-zinc-700 dark:[&_h2]:text-zinc-50",
  "[&_h2:first-child]:mt-0",
  "[&_h3]:mb-3 [&_h3]:mt-10 [&_h3]:font-serif [&_h3]:text-lg [&_h3]:font-bold [&_h3]:text-zinc-900 dark:[&_h3]:text-zinc-50",
  "[&_h4]:mb-2 [&_h4]:mt-8 [&_h4]:text-base [&_h4]:font-bold [&_h4]:text-zinc-900 dark:[&_h4]:text-zinc-50",
  "[&_ul]:my-6 [&_ul]:list-disc [&_ul]:space-y-2 [&_ul]:pl-6",
  "[&_ol]:my-6 [&_ol]:list-decimal [&_ol]:space-y-2 [&_ol]:pl-6",
  "[&_li]:pl-1 [&_li]:marker:text-zinc-400",
  "[&_blockquote]:my-8 [&_blockquote]:border-l-[3px] [&_blockquote]:border-rose-400/70 [&_blockquote]:bg-zinc-50/80 [&_blockquote]:py-3 [&_blockquote]:pl-5 [&_blockquote]:pr-4 [&_blockquote]:text-[16px] [&_blockquote]:leading-relaxed [&_blockquote]:text-zinc-600 dark:[&_blockquote]:border-rose-500/50 dark:[&_blockquote]:bg-zinc-900/40 dark:[&_blockquote]:text-zinc-300",
  "[&_figure]:my-8 [&_figure]:mx-auto [&_figure]:max-w-full [&_figure]:border-0 [&_figure]:bg-transparent [&_figure]:p-0 [&_figure]:shadow-none",
  "[&_figure.bbc-inline-image]:mx-0 [&_figure.bbc-media-embed]:mx-0",
  "[&_figure>img]:block [&_figure>img]:max-h-[min(72vh,560px)] [&_figure>img]:w-full [&_figure>img]:max-w-full [&_figure>img]:rounded-lg [&_figure>img]:object-contain",
  "[&_figure_picture_img]:max-h-[min(72vh,560px)] [&_figure_picture_img]:w-full [&_figure_picture_img]:max-w-full [&_figure_picture_img]:rounded-lg [&_figure_picture_img]:object-contain",
  "[&_figure_figcaption]:mt-2 [&_figure_figcaption]:border-0 [&_figure_figcaption]:bg-transparent [&_figure_figcaption]:px-0 [&_figure_figcaption]:py-0 [&_figure_figcaption]:text-[14px] [&_figure_figcaption]:leading-relaxed [&_figure_figcaption]:text-zinc-600 dark:[&_figure_figcaption]:text-zinc-400",
  "[&_picture]:my-8 [&_picture]:block [&_picture]:max-w-full [&_picture]:border-0 [&_picture]:bg-transparent [&_picture]:p-0",
  "[&_picture_img]:max-h-[min(72vh,560px)] [&_picture_img]:w-full [&_picture_img]:max-w-full [&_picture_img]:rounded-lg [&_picture_img]:object-contain",
  "[&_p>img]:rounded-lg [&_p>img]:max-w-full",
  "[&_img]:max-h-[min(72vh,560px)] [&_img]:object-contain",
  "[&_.bbc-reader-img-caption-text]:-mt-1 [&_.bbc-reader-img-caption-text]:mb-6 [&_.bbc-reader-img-caption-text]:text-[15px] [&_.bbc-reader-img-caption-text]:italic [&_.bbc-reader-img-caption-text]:leading-relaxed [&_.bbc-reader-img-caption-text]:text-zinc-600 dark:[&_.bbc-reader-img-caption-text]:text-zinc-400",
  "[&_iframe]:my-8 [&_iframe]:aspect-video [&_iframe]:h-auto [&_iframe]:min-h-[200px] [&_iframe]:w-full [&_iframe]:max-w-full [&_iframe]:rounded-xl [&_iframe]:border [&_iframe]:border-zinc-200/80 dark:[&_iframe]:border-zinc-700/80",
  "[&_video]:my-8 [&_video]:max-h-[min(70vh,520px)] [&_video]:w-full [&_video]:max-w-full [&_video]:rounded-xl [&_video]:border [&_video]:border-zinc-200/80 dark:[&_video]:border-zinc-700/80",
  "[&_table]:w-full [&_table]:border-collapse [&_table]:text-left [&_table]:text-[13px] sm:[&_table]:text-sm",
  "[&_th]:border [&_th]:border-zinc-200/90 [&_th]:bg-zinc-100/95 [&_th]:px-3 [&_th]:py-2.5 [&_th]:font-semibold [&_th]:text-zinc-800 dark:[&_th]:border-zinc-700 dark:[&_th]:bg-zinc-800/90 dark:[&_th]:text-zinc-100",
  "[&_td]:border [&_td]:border-zinc-200/80 [&_td]:px-3 [&_td]:py-2 [&_td]:text-zinc-700 dark:[&_td]:border-zinc-700 dark:[&_td]:text-zinc-300",
  "[&_tr:nth-child(even)_td]:bg-zinc-50/50 dark:[&_tr:nth-child(even)_td]:bg-zinc-900/25",
  "[&_.bbc-reader-table-wrap]:my-8 [&_.bbc-reader-table-wrap]:overflow-x-auto [&_.bbc-reader-table-wrap]:rounded-xl [&_.bbc-reader-table-wrap]:border [&_.bbc-reader-table-wrap]:border-zinc-200/80 [&_.bbc-reader-table-wrap]:bg-white/80 [&_.bbc-reader-table-wrap]:shadow-sm dark:[&_.bbc-reader-table-wrap]:border-zinc-700 dark:[&_.bbc-reader-table-wrap]:bg-zinc-950/40",
  "[&_a]:font-medium [&_a]:text-rose-700 [&_a]:underline-offset-2 [&_a]:transition-colors hover:[&_a]:text-rose-800 hover:[&_a]:underline dark:[&_a]:text-rose-400 dark:hover:[&_a]:text-rose-300",
  "[&_hr]:my-10 [&_hr]:border-0 [&_hr]:border-t [&_hr]:border-zinc-200 dark:[&_hr]:border-zinc-700",
].join(" ");
