/** Tailwind utility string for scraped Guardian article HTML (no React deps). */
export const GUARDIAN_READ_BODY_CLASS = [
  "guardian-read-content not-prose w-full max-w-none",
  "text-[17px] font-normal leading-7 text-zinc-700 dark:text-zinc-300",
  "[&_p]:mb-6 [&_p]:mt-0 [&_p+p]:mt-0",
  "[&_p:has(>strong:only-child)]:mb-3 [&_p:has(>strong:only-child)]:mt-10 [&_p:has(>strong:only-child):first-child]:mt-0",
  "[&_p:has(>strong:only-child)>strong]:text-[1.05rem] [&_p:has(>strong:only-child)>strong]:font-bold [&_p:has(>strong:only-child)>strong]:tracking-tight [&_p:has(>strong:only-child)>strong]:text-zinc-900 dark:[&_p:has(>strong:only-child)>strong]:text-zinc-50",
  "[&_h2]:mb-4 [&_h2]:mt-12 [&_h2]:scroll-mt-24 [&_h2]:border-b [&_h2]:border-zinc-200/90 [&_h2]:pb-3 [&_h2]:font-serif [&_h2]:text-xl [&_h2]:font-bold [&_h2]:tracking-tight [&_h2]:text-zinc-900 dark:[&_h2]:border-zinc-700 dark:[&_h2]:text-zinc-50",
  "[&_h2:first-child]:mt-0",
  "[&_h3]:mb-3 [&_h3]:mt-10 [&_h3]:font-serif [&_h3]:text-lg [&_h3]:font-bold [&_h3]:text-zinc-900 dark:[&_h3]:text-zinc-50",
  "[&_h4]:mb-2 [&_h4]:mt-8 [&_h4]:text-base [&_h4]:font-bold [&_h4]:text-zinc-900 dark:[&_h4]:text-zinc-50",
  "[&_ul]:my-6 [&_ul]:list-disc [&_ul]:space-y-2 [&_ul]:pl-6",
  "[&_ol]:my-6 [&_ol]:list-decimal [&_ol]:space-y-2 [&_ol]:pl-6",
  "[&_li]:pl-1 [&_li]:marker:text-zinc-400",
  "[&_blockquote]:my-8 [&_blockquote]:border-l-[3px] [&_blockquote]:border-sky-500/70 [&_blockquote]:bg-zinc-50/80 [&_blockquote]:py-3 [&_blockquote]:pl-5 [&_blockquote]:pr-4 [&_blockquote]:text-[16px] [&_blockquote]:leading-relaxed [&_blockquote]:text-zinc-600 dark:[&_blockquote]:border-sky-400/50 dark:[&_blockquote]:bg-zinc-900/40 dark:[&_blockquote]:text-zinc-300",
  "[&_figure]:my-8 [&_figure]:mx-auto [&_figure]:max-w-full [&_figure]:border-0 [&_figure]:bg-transparent [&_figure]:p-0 [&_figure]:shadow-none",
  "[&_figure>img]:block [&_figure>img]:max-h-[min(72vh,560px)] [&_figure>img]:w-full [&_figure>img]:max-w-full [&_figure>img]:rounded-lg [&_figure>img]:object-contain",
  "[&_figure_picture_img]:max-h-[min(72vh,560px)] [&_figure_picture_img]:w-full [&_figure_picture_img]:max-w-full [&_figure_picture_img]:rounded-lg [&_figure_picture_img]:object-contain",
  "[&_figure_figcaption]:mt-2 [&_figure_figcaption]:border-0 [&_figure_figcaption]:bg-transparent [&_figure_figcaption]:px-0 [&_figure_figcaption]:py-0 [&_figure_figcaption]:text-[14px] [&_figure_figcaption]:leading-relaxed [&_figure_figcaption]:text-zinc-600 dark:[&_figure_figcaption]:text-zinc-400",
  "[&_picture]:my-8 [&_picture]:block [&_picture]:max-w-full [&_picture]:border-0 [&_picture]:bg-transparent [&_picture]:p-0",
  "[&_picture_img]:max-h-[min(72vh,560px)] [&_picture_img]:w-full [&_picture_img]:max-w-full [&_picture_img]:rounded-lg [&_picture_img]:object-contain",
  "[&_p>img]:rounded-lg [&_p>img]:max-w-full",
  "[&_img]:max-h-[min(72vh,560px)] [&_img]:object-contain",
  "[&_iframe]:my-8 [&_iframe]:aspect-video [&_iframe]:h-auto [&_iframe]:min-h-[200px] [&_iframe]:w-full [&_iframe]:max-w-full [&_iframe]:rounded-xl [&_iframe]:border [&_iframe]:border-zinc-200/80 dark:[&_iframe]:border-zinc-700/80",
  "[&_video]:my-8 [&_video]:max-h-[min(70vh,520px)] [&_video]:w-full [&_video]:max-w-full [&_video]:rounded-xl [&_video]:border [&_video]:border-zinc-200/80 dark:[&_video]:border-zinc-700/80",
  "[&_table]:w-full [&_table]:border-collapse [&_table]:text-left [&_table]:text-[13px] sm:[&_table]:text-sm",
  "[&_th]:border [&_th]:border-zinc-200/90 [&_th]:bg-zinc-100/95 [&_th]:px-3 [&_th]:py-2.5 [&_th]:font-semibold [&_th]:text-zinc-800 dark:[&_th]:border-zinc-700 dark:[&_th]:bg-zinc-800/90 dark:[&_th]:text-zinc-100",
  "[&_td]:border [&_td]:border-zinc-200/80 [&_td]:px-3 [&_td]:py-2 [&_td]:text-zinc-700 dark:[&_td]:border-zinc-700 dark:[&_td]:text-zinc-300",
  "[&_tr:nth-child(even)_td]:bg-zinc-50/50 dark:[&_tr:nth-child(even)_td]:bg-zinc-900/25",
  "[&_a]:font-medium [&_a]:text-sky-700 [&_a]:underline-offset-2 [&_a]:transition-colors hover:[&_a]:text-sky-800 hover:[&_a]:underline dark:[&_a]:text-sky-400 dark:hover:[&_a]:text-sky-300",
  "[&_hr]:my-10 [&_hr]:border-0 [&_hr]:border-t [&_hr]:border-zinc-200 dark:[&_hr]:border-zinc-700",
  // <time> — live blog timestamps
  "[&_time]:block [&_time]:mb-1 [&_time]:text-[12px] [&_time]:font-semibold [&_time]:uppercase [&_time]:tracking-widest [&_time]:text-zinc-400 dark:[&_time]:text-zinc-500",
  // <aside> — related content / pullquote boxes Guardian adds
  "[&_aside]:my-8 [&_aside]:rounded-xl [&_aside]:border [&_aside]:border-zinc-200/80 [&_aside]:bg-zinc-50/70 [&_aside]:px-5 [&_aside]:py-4 [&_aside]:text-[15px] [&_aside]:text-zinc-600 dark:[&_aside]:border-zinc-700/60 dark:[&_aside]:bg-zinc-900/40 dark:[&_aside]:text-zinc-300",
  "[&_aside_h2]:mt-0 [&_aside_h2]:border-none [&_aside_h2]:pb-0 [&_aside_h2]:text-base",
  "[&_aside_p]:mb-3 [&_aside_p:last-child]:mb-0",
  // <details> / <summary> — spoilers / expandable sections
  "[&_details]:my-6 [&_details]:rounded-lg [&_details]:border [&_details]:border-zinc-200/80 [&_details]:px-4 [&_details]:py-3 dark:[&_details]:border-zinc-700/60",
  "[&_summary]:cursor-pointer [&_summary]:select-none [&_summary]:font-semibold [&_summary]:text-zinc-800 [&_summary]:outline-none dark:[&_summary]:text-zinc-100",
  "[&_details[open]_summary]:mb-3",
  // <mark> — highlighted text
  "[&_mark]:rounded-sm [&_mark]:bg-yellow-100 [&_mark]:px-0.5 [&_mark]:text-zinc-900 dark:[&_mark]:bg-yellow-500/20 dark:[&_mark]:text-zinc-100",
  // <code> / <pre> — inline code and code blocks
  "[&_code]:rounded [&_code]:bg-zinc-100 [&_code]:px-1 [&_code]:py-0.5 [&_code]:text-[13px] [&_code]:font-mono [&_code]:text-zinc-800 dark:[&_code]:bg-zinc-800 dark:[&_code]:text-zinc-200",
  "[&_pre]:my-6 [&_pre]:overflow-x-auto [&_pre]:rounded-xl [&_pre]:bg-zinc-100 [&_pre]:p-4 [&_pre]:text-[13px] [&_pre]:leading-relaxed dark:[&_pre]:bg-zinc-800",
  "[&_pre_code]:bg-transparent [&_pre_code]:p-0",
  // Live blog update blocks — Guardian wraps each update in <article> inside the main <article>
  "[&_article]:mt-10 [&_article]:border-t [&_article]:border-zinc-200/70 [&_article]:pt-8 dark:[&_article]:border-zinc-700/50",
  "[&_article:first-child]:mt-0 [&_article:first-child]:border-none [&_article:first-child]:pt-0",
].join(" ");
