import { engnovateListeningAudioCandidates } from "./listening-audio-engnovate";
export type ListeningAnswer = string | string[];
export type ListeningTest = {
    id: string;
    label: string;
    testNumber: number;
    correctAnswers?: Record<number, ListeningAnswer>;
};
export type ListeningSet = {
    id: string;
    title: string;
    examLabel: string;
    cambridgeNumber: number;
    variant: "academic" | "general";
    tests: ListeningTest[];
};
export const listeningSets: ListeningSet[] = [
    {
        id: "cambridge-20",
        title: "Cambridge IELTS 20",
        examLabel: "Cam 20 Academic",
        cambridgeNumber: 20,
        variant: "academic",
        tests: [
            {
                id: "test-1",
                label: "Test 1",
                testNumber: 1,
                correctAnswers: {
                    1: "fish",
                    2: "roof",
                    3: "spanish",
                    4: "vegetarian",
                    5: "audley",
                    6: "hotel",
                    7: "reviews",
                    8: "local",
                    9: "30",
                    10: "average",
                    11: "A",
                    12: "B",
                    13: "C",
                    14: "A",
                    15: "B",
                    16: "C",
                    17: ["A", "E"],
                    18: ["A", "E"],
                    19: ["C", "E"],
                    20: ["C", "E"],
                    21: ["C", "E"],
                    22: ["C", "E"],
                    23: ["A", "C"],
                    24: ["A", "C"],
                    25: ["A", "B"],
                    26: ["A", "B"],
                    27: "A",
                    28: "B",
                    29: "A",
                    30: "C",
                    31: "factories",
                    32: "dead",
                    33: "whale",
                    34: "apartments",
                    35: "park",
                    36: "art",
                    37: "beaches",
                    38: "ferry",
                    39: "bikes",
                    40: "drone",
                },
            },
            {
                id: "test-2",
                label: "Test 2",
                testNumber: 2,
                correctAnswers: {
                    1: "break",
                    2: "time",
                    3: "shower",
                    4: "money",
                    5: "memory",
                    6: "lifting",
                    7: "fall",
                    8: "taxi",
                    9: "insurance",
                    10: "stress",
                    11: "D",
                    12: "I",
                    13: "H",
                    14: "E",
                    15: "A",
                    16: "B",
                    17: "B",
                    18: "C",
                    19: "B",
                    20: "A",
                    21: "D",
                    22: "G",
                    23: "B",
                    24: "A",
                    25: "E",
                    26: "C",
                    27: "C",
                    28: "A",
                    29: "B",
                    30: "C",
                    31: ["photos", "photographs", "pictures"],
                    32: "vegan",
                    33: ["chefs", "cooks"],
                    34: ["journalists", "reporters"],
                    35: "health",
                    36: "coffee",
                    37: "environment",
                    38: "reputation",
                    39: ["price", "cost"],
                    40: "soil",
                },
            },
            {
                id: "test-3",
                label: "Test 3",
                testNumber: 3,
                correctAnswers: {
                    1: "239",
                    2: "modern",
                    3: "lamp",
                    4: "aaron",
                    5: "damage",
                    6: "electronic",
                    7: "insurance",
                    8: "space",
                    9: "app",
                    10: "exchanges",
                    11: "B",
                    12: "A",
                    13: "A",
                    14: "C",
                    15: "B",
                    16: "C",
                    17: "B",
                    18: "A",
                    19: "G",
                    20: "E",
                    21: "B",
                    22: "A",
                    23: "C",
                    24: "A",
                    25: "C",
                    26: "B",
                    27: "F",
                    28: "E",
                    29: "B",
                    30: "D",
                    31: "adaptation",
                    32: "cognitive",
                    33: "desks",
                    34: "taps",
                    35: "blue",
                    36: "voice",
                    37: "pregnant",
                    38: "shoulders",
                    39: "police",
                    40: "temperature",
                },
            },
            {
                id: "test-4",
                label: "Test 4",
                testNumber: 4,
                correctAnswers: {
                    1: ["kings", "king's"],
                    2: "125",
                    3: "walking",
                    4: "boat",
                    5: "tuesday",
                    6: "space",
                    7: "vegetarian",
                    8: ["2.30", "2:30"],
                    9: "75",
                    10: "port",
                    11: ["B", "C"],
                    12: ["B", "C"],
                    13: ["A", "C"],
                    14: ["A", "C"],
                    15: "D",
                    16: "F",
                    17: "B",
                    18: "H",
                    19: "C",
                    20: "G",
                    21: ["C", "E"],
                    22: ["C", "E"],
                    23: ["A", "C"],
                    24: ["A", "C"],
                    25: "C",
                    26: "A",
                    27: "A",
                    28: "B",
                    29: "B",
                    30: "C",
                    31: "rats",
                    32: "snakes",
                    33: "tourism",
                    34: "traffic",
                    35: "rain",
                    36: "poison",
                    37: "building",
                    38: "dog",
                    39: "noise",
                    40: "combination",
                },
            },
        ],
    },
    {
        id: "cambridge-19",
        title: "Cambridge IELTS 19",
        examLabel: "Cam 19 Academic",
        cambridgeNumber: 19,
        variant: "academic",
        tests: [
            {
                id: "test-1",
                label: "Test 1",
                testNumber: 1,
                correctAnswers: {
                    1: "69",
                    2: "stream",
                    3: "data",
                    4: "map",
                    5: "visitors",
                    6: "sounds",
                    7: "freedom",
                    8: "skills",
                    9: "4.95",
                    10: "leaders",
                    11: "B",
                    12: "A",
                    13: "B",
                    14: "C",
                    15: "A",
                    16: "G",
                    17: "C",
                    18: "B",
                    19: "D",
                    20: "A",
                    21: ["B", "D"],
                    22: ["B", "D"],
                    23: ["A", "E"],
                    24: ["A", "E"],
                    25: "D",
                    26: "G",
                    27: "C",
                    28: "B",
                    29: "F",
                    30: "H",
                    31: "walls",
                    32: "son",
                    33: "fuel",
                    34: "oxygen",
                    35: "rectangular",
                    36: "lamps",
                    37: "family",
                    38: "winter",
                    39: "soil",
                    40: "rain",
                },
            },
            {
                id: "test-2",
                label: "Test 2",
                testNumber: 2,
                correctAnswers: {
                    1: "mathieson",
                    2: "beginners",
                    3: "college",
                    4: "new",
                    5: ["11", "eleven"],
                    6: "instrument",
                    7: "ear",
                    8: "clapping",
                    9: "recording",
                    10: "alone",
                    11: "A",
                    12: "B",
                    13: "A",
                    14: "B",
                    15: "C",
                    16: "A",
                    17: ["C", "E"],
                    18: ["C", "E"],
                    19: ["A", "B"],
                    20: ["A", "B"],
                    21: "A",
                    22: "B",
                    23: "B",
                    24: "B",
                    25: "E",
                    26: "B",
                    27: "A",
                    28: "C",
                    29: "C",
                    30: "A",
                    31: "move",
                    32: "short",
                    33: "discs",
                    34: "oxygen",
                    35: "tube",
                    36: "temperatures",
                    37: "protein",
                    38: "space",
                    39: "seaweed",
                    40: "endangered",
                },
            },
            {
                id: "test-3",
                label: "Test 3",
                testNumber: 3,
                correctAnswers: {
                    1: ["harbour", "harbor"],
                    2: "bridge",
                    3: ["3.30", "3:30", "three thirty"],
                    4: "rose",
                    5: "sign",
                    6: "purple",
                    7: "samphire",
                    8: "melon",
                    9: "coconut",
                    10: "strawberry",
                    11: "C",
                    12: "D",
                    13: "F",
                    14: "G",
                    15: "B",
                    16: "H",
                    17: ["D", "E"],
                    18: ["D", "E"],
                    19: ["B", "C"],
                    20: ["B", "C"],
                    21: "C",
                    22: "B",
                    23: "A",
                    24: "A",
                    25: "C",
                    26: "C",
                    27: "H",
                    28: "E",
                    29: "B",
                    30: "F",
                    31: "clothing",
                    32: "mouths",
                    33: "salt",
                    34: "toothpaste",
                    35: ["fertilisers", "fertilizers"],
                    36: "nutrients",
                    37: "growth",
                    38: "weight",
                    39: "acid",
                    40: "society",
                },
            },
            {
                id: "test-4",
                label: "Test 4",
                testNumber: 4,
                correctAnswers: {
                    1: "kaeden",
                    2: ["locker", "lockers"],
                    3: "passport",
                    4: "uniform",
                    5: ["third", "3rd"],
                    6: ["0412 665 903", "0412665903"],
                    7: "yellow",
                    8: "plastic",
                    9: "ice",
                    10: "gloves",
                    11: ["C", "E"],
                    12: ["C", "E"],
                    13: ["A", "D"],
                    14: ["A", "D"],
                    15: "A",
                    16: "B",
                    17: "C",
                    18: "A",
                    19: "C",
                    20: "B",
                    21: "A",
                    22: "C",
                    23: "A",
                    24: "B",
                    25: "C",
                    26: "D",
                    27: "F",
                    28: "A",
                    29: "C",
                    30: "G",
                    31: "competition",
                    32: "food",
                    33: "disease",
                    34: "agriculture",
                    35: "maps",
                    36: "cattle",
                    37: "speed",
                    38: "monkeys",
                    39: "fishing",
                    40: "flooding",
                },
            },
        ],
    },
    {
        id: "cambridge-18",
        title: "Cambridge IELTS 18",
        examLabel: "Cam 18 Academic",
        cambridgeNumber: 18,
        variant: "academic",
        tests: [
            {
                id: "test-1",
                label: "Test 1",
                testNumber: 1,
                correctAnswers: {
                    1: ["dw30 7yz", "dw307yz"],
                    2: ["24 april", "24th april", "april 24"],
                    3: "dentist",
                    4: "parking",
                    5: "claxby",
                    6: "late",
                    7: "evening",
                    8: "supermarket",
                    9: "pollution",
                    10: "storage",
                    11: "C",
                    12: "A",
                    13: "A",
                    14: ["B", "E"],
                    15: ["B", "E"],
                    16: "B",
                    17: "G",
                    18: "D",
                    19: "A",
                    20: "F",
                    21: "A",
                    22: "B",
                    23: "A",
                    24: "C",
                    25: "B",
                    26: "A",
                    27: ["B", "E"],
                    28: ["B", "E"],
                    29: ["A", "C"],
                    30: ["A", "C"],
                    31: "fences",
                    32: "family",
                    33: "helicopters",
                    34: "stress",
                    35: "sides",
                    36: "breathing",
                    37: "feet",
                    38: "employment",
                    39: "weapons",
                    40: "tourism",
                },
            },
            {
                id: "test-2",
                label: "Test 2",
                testNumber: 2,
                correctAnswers: {
                    1: "training",
                    2: "discount",
                    3: "taxi",
                    4: "service",
                    5: "english",
                    6: "wivenhoe",
                    7: "equipment",
                    8: "9.75",
                    9: "deliveries",
                    10: "sunday",
                    11: ["B", "E"],
                    12: ["B", "E"],
                    13: ["B", "C"],
                    14: ["B", "C"],
                    15: "G",
                    16: "C",
                    17: "D",
                    18: "B",
                    19: "H",
                    20: "A",
                    21: "C",
                    22: "A",
                    23: "B",
                    24: "B",
                    25: ["A", "B"],
                    26: ["A", "B"],
                    27: "D",
                    28: "A",
                    29: "C",
                    30: "F",
                    31: "convenient",
                    32: "suits",
                    33: "tailor",
                    34: "profession",
                    35: "visible",
                    36: ["string", "strings"],
                    37: ["waist", "waists"],
                    38: "perfume",
                    39: "image",
                    40: "handbag",
                },
            },
            {
                id: "test-3",
                label: "Test 3",
                testNumber: 3,
                correctAnswers: {
                    1: "marrowfield",
                    2: "relative",
                    3: ["socialise", "socialize"],
                    4: "full",
                    5: "domestic life",
                    6: "clouds",
                    7: "timing",
                    8: "animal magic",
                    9: ["movement", "animal movement"],
                    10: "dark",
                    11: ["B", "C"],
                    12: ["B", "C"],
                    13: ["B", "D"],
                    14: ["B", "D"],
                    15: "C",
                    16: "B",
                    17: "B",
                    18: "C",
                    19: "A",
                    20: "A",
                    21: ["A", "E"],
                    22: ["A", "E"],
                    23: ["B", "D"],
                    24: ["B", "D"],
                    25: "G",
                    26: "E",
                    27: "B",
                    28: "C",
                    29: "F",
                    30: "A",
                    31: "technical",
                    32: "cheap",
                    33: "thousands",
                    34: "identification",
                    35: "tracking",
                    36: "military",
                    37: "location",
                    38: "prediction",
                    39: "database",
                    40: "trust",
                },
            },
            {
                id: "test-4",
                label: "Test 4",
                testNumber: 4,
                correctAnswers: {
                    1: "receptionist",
                    2: "medical",
                    3: "chastons",
                    4: "appointments",
                    5: "database",
                    6: "experience",
                    7: "confident",
                    8: "temporary",
                    9: ["1.15", "1:15"],
                    10: "parking",
                    11: "B",
                    12: "A",
                    13: "A",
                    14: "C",
                    15: "F",
                    16: "G",
                    17: "E",
                    18: "A",
                    19: "C",
                    20: "B",
                    21: ["B", "D"],
                    22: ["B", "D"],
                    23: "D",
                    24: "A",
                    25: "C",
                    26: "G",
                    27: "F",
                    28: "A",
                    29: "B",
                    30: "C",
                    31: "plot",
                    32: "poverty",
                    33: "europe",
                    34: "poetry",
                    35: "drawings",
                    36: "furniture",
                    37: "lamps",
                    38: ["harbour", "harbor"],
                    39: "children",
                    40: "relatives",
                },
            },
        ],
    },
    {
        id: "cambridge-17",
        title: "Cambridge IELTS 17",
        examLabel: "Cam 17 Academic",
        cambridgeNumber: 17,
        variant: "academic",
        tests: [
            {
                id: "test-1",
                label: "Test 1",
                testNumber: 1,
                correctAnswers: {
                    1: "litter",
                    2: "dogs",
                    3: "insects",
                    4: "butterflies",
                    5: "wall",
                    6: "island",
                    7: "boots",
                    8: "beginners",
                    9: "spoons",
                    10: ["35", "thirty five"],
                    11: "A",
                    12: "C",
                    13: "B",
                    14: "B",
                    15: ["A", "D"],
                    16: ["A", "D"],
                    17: ["B", "C"],
                    18: ["B", "C"],
                    19: ["D", "E"],
                    20: ["D", "E"],
                    21: "A",
                    22: "B",
                    23: "B",
                    24: "A",
                    25: "C",
                    26: "C",
                    27: "A",
                    28: "E",
                    29: "F",
                    30: "C",
                    31: "puzzle",
                    32: "logic",
                    33: "confusion",
                    34: "meditation",
                    35: "stone",
                    36: "coins",
                    37: "tree",
                    38: "breathing",
                    39: "paper",
                    40: "anxiety",
                },
            },
            {
                id: "test-2",
                label: "Test 2",
                testNumber: 2,
                correctAnswers: {
                    1: "collecting",
                    2: "records",
                    3: "west",
                    4: "transport",
                    5: "art",
                    6: "hospital",
                    7: "garden",
                    8: "quiz",
                    9: "tickets",
                    10: "poster",
                    11: "B",
                    12: "C",
                    13: "C",
                    14: "B",
                    15: "D",
                    16: "C",
                    17: "G",
                    18: "A",
                    19: "E",
                    20: "F",
                    21: ["D", "E"],
                    22: ["D", "E"],
                    23: "D",
                    24: "C",
                    25: "A",
                    26: "E",
                    27: "F",
                    28: "B",
                    29: "C",
                    30: "C",
                    31: ["321,000", "321000", "321 000"],
                    32: "vocabulary",
                    33: "podcast",
                    34: "smartphones",
                    35: "bilingual",
                    36: "playground",
                    37: "picture",
                    38: "grammar",
                    39: "identity",
                    40: "fluent",
                },
            },
            {
                id: "test-3",
                label: "Test 3",
                testNumber: 3,
                correctAnswers: {
                    1: "family",
                    2: "fit",
                    3: "hotels",
                    4: "carrowniskey",
                    5: "week",
                    6: "bay",
                    7: "september",
                    8: ["19", "nineteen"],
                    9: ["30", "thirty"],
                    10: "boots",
                    11: ["B", "E"],
                    12: ["B", "E"],
                    13: "C",
                    14: "C",
                    15: "A",
                    16: "E",
                    17: "D",
                    18: "G",
                    19: "F",
                    20: "C",
                    21: "B",
                    22: "A",
                    23: "A",
                    24: "B",
                    25: "C",
                    26: "A",
                    27: "D",
                    28: "B",
                    29: "F",
                    30: "H",
                    31: "mud",
                    32: "feathers",
                    33: "shape",
                    34: "moon",
                    35: "neck",
                    36: "evidence",
                    37: "destinations",
                    38: "oceans",
                    39: "recovery",
                    40: "atlas",
                },
            },
            {
                id: "test-4",
                label: "Test 4",
                testNumber: 4,
                correctAnswers: {
                    1: ["floor", "floors"],
                    2: "fridge",
                    3: "shirts",
                    4: "windows",
                    5: "balcony",
                    6: "electrician",
                    7: "dust",
                    8: "police",
                    9: "training",
                    10: "review",
                    11: "A",
                    12: "A",
                    13: "A",
                    14: "C",
                    15: "A",
                    16: "C",
                    17: "B",
                    18: "C",
                    19: "B",
                    20: "A",
                    21: ["C", "E"],
                    22: ["C", "E"],
                    23: ["A", "D"],
                    24: ["A", "D"],
                    25: "B",
                    26: "F",
                    27: "A",
                    28: "D",
                    29: "C",
                    30: "G",
                    31: "golden",
                    32: "healthy",
                    33: "climate",
                    34: ["rock", "rocks"],
                    35: "diameter",
                    36: "tube",
                    37: "fire",
                    38: "steam",
                    39: "cloudy",
                    40: ["litre", "liter"],
                },
            },
        ],
    },
    {
        id: "cambridge-16",
        title: "Cambridge IELTS 16",
        examLabel: "Cam 16 Academic",
        cambridgeNumber: 16,
        variant: "academic",
        tests: [
            {
                id: "test-1",
                label: "Test 1",
                testNumber: 1,
                correctAnswers: {
                    1: "egg",
                    2: "tower",
                    3: "car",
                    4: "animals",
                    5: "bridge",
                    6: ["movie", "film"],
                    7: "decorate",
                    8: "wednesdays",
                    9: "fradstone",
                    10: "parking",
                    11: "C",
                    12: "A",
                    13: "B",
                    14: "C",
                    15: "H",
                    16: "C",
                    17: "G",
                    18: "B",
                    19: "I",
                    20: "A",
                    21: ["C", "E"],
                    22: ["C", "E"],
                    23: ["B", "E"],
                    24: ["B", "E"],
                    25: "D",
                    26: "C",
                    27: "A",
                    28: "H",
                    29: "F",
                    30: "G",
                    31: "practical",
                    32: "publication",
                    33: "choices",
                    34: "negative",
                    35: "play",
                    36: "capitalism",
                    37: "depression",
                    38: "logic",
                    39: "opportunity",
                    40: ["practice", "practise"],
                },
            },
            {
                id: "test-2",
                label: "Test 2",
                testNumber: 2,
                correctAnswers: {
                    1: "frame",
                    2: "195",
                    3: "payment",
                    4: "grandparents",
                    5: ["colour", "color"],
                    6: "hand",
                    7: "background",
                    8: "focus",
                    9: ["ten", "10 days"],
                    10: "plastic",
                    11: "C",
                    12: "B",
                    13: "A",
                    14: "A",
                    15: "C",
                    16: "D",
                    17: "A",
                    18: "B",
                    19: ["B", "C"],
                    20: ["B", "C"],
                    21: "B",
                    22: "A",
                    23: "C",
                    24: "C",
                    25: "history",
                    26: "paper",
                    27: ["humans", "people"],
                    28: "stress",
                    29: "graph",
                    30: "evaluate",
                    31: "creativity",
                    32: "therapy",
                    33: "fitness",
                    34: "balance",
                    35: "brain",
                    36: "motivation",
                    37: "isolation",
                    38: "calories",
                    39: "obesity",
                    40: "habit",
                },
            },
            {
                id: "test-3",
                label: "Test 3",
                testNumber: 3,
                correctAnswers: {
                    1: "park",
                    2: "blue",
                    3: "reference",
                    4: "story",
                    5: "rain",
                    6: "snack",
                    7: "medication",
                    8: "helmet",
                    9: "tent",
                    10: "199",
                    11: ["A", "C"],
                    12: ["A", "C"],
                    13: ["B", "C"],
                    14: ["B", "C"],
                    15: "D",
                    16: "F",
                    17: "A",
                    18: "H",
                    19: "C",
                    20: "G",
                    21: ["C", "D"],
                    22: ["C", "D"],
                    23: ["C", "E"],
                    24: ["C", "E"],
                    25: "C",
                    26: "A",
                    27: "B",
                    28: "A",
                    29: "A",
                    30: "C",
                    31: "grandmother",
                    32: "decade",
                    33: "equipment",
                    34: "economic",
                    35: "basic",
                    36: "round",
                    37: "bone",
                    38: "rough",
                    39: "style",
                    40: "sheep",
                },
            },
            {
                id: "test-4",
                label: "Test 4",
                testNumber: 4,
                correctAnswers: {
                    1: "28th",
                    2: "550",
                    3: "chervil",
                    4: "garage",
                    5: "garden",
                    6: "parking",
                    7: "wood",
                    8: "bridge",
                    9: "monument",
                    10: "march",
                    11: "C",
                    12: "A",
                    13: "B",
                    14: "B",
                    15: "C",
                    16: "F",
                    17: "A",
                    18: "I",
                    19: "E",
                    20: "H",
                    21: ["B", "C"],
                    22: ["B", "C"],
                    23: ["B", "C"],
                    24: ["B", "C"],
                    25: "C",
                    26: "F",
                    27: "D",
                    28: "E",
                    29: "B",
                    30: "A",
                    31: ["spice", "spices"],
                    32: ["colony", "settlement"],
                    33: "fat",
                    34: "head",
                    35: "movement",
                    36: ["balance", "balancing"],
                    37: "brain",
                    38: "smell",
                    39: "rats",
                    40: "forest",
                },
            },
        ],
    },
    {
        id: "cambridge-15",
        title: "Cambridge IELTS 15",
        examLabel: "Cam 15 Academic",
        cambridgeNumber: 15,
        variant: "academic",
        tests: [
            {
                id: "test-1",
                label: "Test 1",
                testNumber: 1,
                correctAnswers: {
                    1: "jamieson",
                    2: "afternoon",
                    3: "communication",
                    4: "week",
                    5: ["10", "ten"],
                    6: "suit",
                    7: "passport",
                    8: "personality",
                    9: "feedback",
                    10: "time",
                    11: "A",
                    12: "B",
                    13: "A",
                    14: "C",
                    15: "river",
                    16: "1422",
                    17: "top",
                    18: "pass",
                    19: "steam",
                    20: "capital",
                    21: "G",
                    22: "F",
                    23: "A",
                    24: "E",
                    25: "B",
                    26: "C",
                    27: "C",
                    28: "A",
                    29: ["B", "D"],
                    30: ["B", "D"],
                    31: "shelter",
                    32: "oil",
                    33: "roads",
                    34: "insects",
                    35: ["grass", "grasses"],
                    36: "water",
                    37: "soil",
                    38: "dry",
                    39: "simple",
                    40: ["nest", "nests"],
                },
            },
            {
                id: "test-2",
                label: "Test 2",
                testNumber: 2,
                correctAnswers: {
                    1: "eustatis",
                    2: "review",
                    3: "dance",
                    4: "chat",
                    5: "healthy",
                    6: "posters",
                    7: "wood",
                    8: "lake",
                    9: "insects",
                    10: "blog",
                    11: "C",
                    12: "A",
                    13: "B",
                    14: "C",
                    15: "E",
                    16: "C",
                    17: "B",
                    18: "A",
                    19: "G",
                    20: "D",
                    21: ["B", "D"],
                    22: ["B", "D"],
                    23: ["B", "C"],
                    24: ["B", "C"],
                    25: "G",
                    26: "B",
                    27: "D",
                    28: "C",
                    29: "H",
                    30: "F",
                    31: "irrigation",
                    32: "women",
                    33: ["wire", "wires"],
                    34: ["seed", "seeds"],
                    35: "posts",
                    36: "transport",
                    37: "preservation",
                    38: ["fish", "fishes"],
                    39: "bees",
                    40: "design",
                },
            },
            {
                id: "test-3",
                label: "Test 3",
                testNumber: 3,
                correctAnswers: {
                    1: "furniture",
                    2: "meetings",
                    3: "diary",
                    4: ["detail", "details"],
                    5: ["1", "one year", "one"],
                    6: "deliveries",
                    7: "tidy",
                    8: "team",
                    9: "heavy",
                    10: "customer",
                    11: "B",
                    12: "A",
                    13: "C",
                    14: "B",
                    15: "C",
                    16: "B",
                    17: ["B", "D"],
                    18: ["B", "D"],
                    19: ["A", "E"],
                    20: ["A", "E"],
                    21: "page",
                    22: "size",
                    23: ["graphic", "graphics"],
                    24: "structure",
                    25: "purpose",
                    26: ["assumption", "assumptions"],
                    27: "A",
                    28: "C",
                    29: "C",
                    30: "B",
                    31: "mud",
                    32: "clay",
                    33: "metal",
                    34: "hair",
                    35: ["bath", "baths"],
                    36: ["disease", "diseases"],
                    37: "perfume",
                    38: "salt",
                    39: "science",
                    40: "tax",
                },
            },
            {
                id: "test-4",
                label: "Test 4",
                testNumber: 4,
                correctAnswers: {
                    1: "journalist",
                    2: "shopping",
                    3: "staunfirth",
                    4: "return",
                    5: "23.70",
                    6: "online",
                    7: "delay",
                    8: "information",
                    9: ["platform", "platforms"],
                    10: "parking",
                    11: "D",
                    12: "C",
                    13: "G",
                    14: "H",
                    15: "A",
                    16: "E",
                    17: ["A", "D"],
                    18: ["A", "D"],
                    19: ["A", "C"],
                    20: ["A", "C"],
                    21: "B",
                    22: "A",
                    23: "B",
                    24: "A",
                    25: "A",
                    26: "A",
                    27: "B",
                    28: "B",
                    29: "A",
                    30: "C",
                    31: "wealth",
                    32: "technology",
                    33: "power",
                    34: ["textile", "textiles"],
                    35: "machines",
                    36: "newspapers",
                    37: "local",
                    38: "lighting",
                    39: "windows",
                    40: "advertising",
                },
            },
        ],
    },
    {
        id: "cambridge-14",
        title: "Cambridge IELTS 14",
        examLabel: "Cam 14 Academic",
        cambridgeNumber: 14,
        variant: "academic",
        tests: [
            {
                id: "test-1",
                label: "Test 1",
                testNumber: 1,
                correctAnswers: {
                    1: "canadian",
                    2: "furniture",
                    3: "park",
                    4: ["250", "250 sterling"],
                    5: "phone",
                    6: ["10 september", "10th september", "september 10"],
                    7: "museum",
                    8: "time",
                    9: ["blond", "blonde"],
                    10: ["87954 82361", "8795482361"],
                    11: ["A", "C"],
                    12: ["A", "C"],
                    13: ["B", "E"],
                    14: ["B", "E"],
                    15: "B",
                    16: "B",
                    17: "C",
                    18: "A",
                    19: "A",
                    20: "C",
                    21: "B",
                    22: "A",
                    23: "C",
                    24: "B",
                    25: "A",
                    26: "B",
                    27: "A",
                    28: "F",
                    29: "G",
                    30: "C",
                    31: "industry",
                    32: "constant",
                    33: "direction",
                    34: "floor",
                    35: "predictable",
                    36: "bay",
                    37: "gates",
                    38: "fuel",
                    39: "jobs",
                    40: "migration",
                },
            },
            {
                id: "test-2",
                label: "Test 2",
                testNumber: 2,
                correctAnswers: {
                    1: "219 442 9785",
                    2: ["10 october", "10th october", "october 10"],
                    3: "manager",
                    4: "cawley",
                    5: "knee",
                    6: ["3 weeks", "3"],
                    7: "tennis",
                    8: "running",
                    9: "shoulder",
                    10: "vitamins",
                    11: "B",
                    12: "C",
                    13: "C",
                    14: "B",
                    15: "A",
                    16: "H",
                    17: "D",
                    18: "F",
                    19: "A",
                    20: "E",
                    21: "B",
                    22: "C",
                    23: "A",
                    24: "A",
                    25: "E",
                    26: "D",
                    27: "A",
                    28: "H",
                    29: "G",
                    30: "C",
                    31: "dances",
                    32: "survival",
                    33: "clouds",
                    34: "festivals",
                    35: "comets",
                    36: "sky",
                    37: "instruments",
                    38: "thermometer",
                    39: "storms",
                    40: "telegraph",
                },
            },
            {
                id: "test-3",
                label: "Test 3",
                testNumber: 3,
                correctAnswers: {
                    1: "tesla",
                    2: "microphone",
                    3: "exhibition",
                    4: ["wifi", "wi-fi"],
                    5: "45",
                    6: "135",
                    7: "pool",
                    8: "airport",
                    9: "sea",
                    10: "clubs",
                    11: ["A", "E"],
                    12: ["A", "E"],
                    13: ["B", "E"],
                    14: ["B", "E"],
                    15: "F",
                    16: "A",
                    17: "E",
                    18: "G",
                    19: "D",
                    20: "C",
                    21: ["50", "fifty"],
                    22: "regional",
                    23: "carnival",
                    24: "drummer",
                    25: "film",
                    26: "parade",
                    27: "D",
                    28: "B",
                    29: "E",
                    30: "F",
                    31: "violin",
                    32: "energy",
                    33: "complex",
                    34: "opera",
                    35: "disturbing",
                    36: "clarinet",
                    37: "diversity",
                    38: "physics",
                    39: "dance",
                    40: "olympics",
                },
            },
            {
                id: "test-4",
                label: "Test 4",
                testNumber: 4,
                correctAnswers: {
                    1: "85",
                    2: "roses",
                    3: "trees",
                    4: "stage",
                    5: "speech",
                    6: "support",
                    7: "cabins",
                    8: "C",
                    9: "A",
                    10: "B",
                    11: "G",
                    12: "D",
                    13: "A",
                    14: "E",
                    15: "F",
                    16: "B",
                    17: ["B", "D"],
                    18: ["B", "D"],
                    19: ["A", "D"],
                    20: ["A", "D"],
                    21: "A",
                    22: "C",
                    23: "A",
                    24: "B",
                    25: "B",
                    26: "F",
                    27: "E",
                    28: "C",
                    29: "B",
                    30: "G",
                    31: "spring",
                    32: "tools",
                    33: "maps",
                    34: "heavy",
                    35: "marble",
                    36: "light",
                    37: ["camera", "cameras"],
                    38: "medical",
                    39: "eyes",
                    40: "wine",
                },
            },
        ],
    },
    {
        id: "cambridge-13",
        title: "Cambridge IELTS 13",
        examLabel: "Cam 13 Academic",
        cambridgeNumber: 13,
        variant: "academic",
        tests: [
            {
                id: "test-1",
                label: "Test 1",
                testNumber: 1,
                correctAnswers: {
                    1: "choose",
                    2: "private",
                    3: ["20", "twenty", "twenty percent"],
                    4: "healthy",
                    5: "bones",
                    6: "lecture",
                    7: "arretsa",
                    8: "vegetarian",
                    9: "market",
                    10: "knife",
                    11: "B",
                    12: "C",
                    13: "B",
                    14: "E",
                    15: "D",
                    16: "B",
                    17: "G",
                    18: "C",
                    19: "H",
                    20: "I",
                    21: "A",
                    22: "C",
                    23: "B",
                    24: "C",
                    25: "B",
                    26: "G",
                    27: "C",
                    28: "H",
                    29: "A",
                    30: "E",
                    31: "crow",
                    32: "cliffs",
                    33: "speed",
                    34: ["brain", "brains"],
                    35: "food",
                    36: ["behaviour", "behavior", "behaviours", "behaviors"],
                    37: "new",
                    38: "new",
                    39: ["tail", "tails"],
                    40: "permanent",
                },
            },
            {
                id: "test-2",
                label: "Test 2",
                testNumber: 2,
                correctAnswers: {
                    1: "races",
                    2: "insurance",
                    3: "jerriz",
                    4: ["25", "twenty-five", "twenty five"],
                    5: "stadium",
                    6: "park",
                    7: "coffee",
                    8: "leader",
                    9: "route",
                    10: "lights",
                    11: "C",
                    12: "B",
                    13: "C",
                    14: "B",
                    15: "B",
                    16: "A",
                    17: ["C", "E"],
                    18: ["C", "E"],
                    19: ["B", "D"],
                    20: ["B", "D"],
                    21: "B",
                    22: "A",
                    23: "C",
                    24: "C",
                    25: "A",
                    26: "A",
                    27: "C",
                    28: "D",
                    29: "G",
                    30: "B",
                    31: "location",
                    32: "world",
                    33: "personal",
                    34: "attention",
                    35: "name",
                    36: "network",
                    37: "frequency",
                    38: ["colour", "color"],
                    39: "brain",
                    40: "self",
                },
            },
            {
                id: "test-3",
                label: "Test 3",
                testNumber: 3,
                correctAnswers: {
                    1: "850",
                    2: ["bike", "bicycle"],
                    3: "parking",
                    4: ["30", "thirty"],
                    5: ["weekend", "weekends"],
                    6: "cinema",
                    7: "hospital",
                    8: "dentist",
                    9: "thursday",
                    10: ["café", "cafe"],
                    11: "F",
                    12: "D",
                    13: "A",
                    14: "B",
                    15: "C",
                    16: "G",
                    17: ["B", "C"],
                    18: ["B", "C"],
                    19: ["B", "D"],
                    20: ["B", "D"],
                    21: "C",
                    22: "A",
                    23: "A",
                    24: "B",
                    25: "C",
                    26: "F",
                    27: "H",
                    28: "D",
                    29: "A",
                    30: "E",
                    31: ["tongue", "tongues"],
                    32: "plants",
                    33: "snakes",
                    34: "sky",
                    35: ["partner", "partners"],
                    36: "contact",
                    37: "protection",
                    38: ["tail", "tails"],
                    39: "steps",
                    40: ["injury", "injuries"],
                },
            },
            {
                id: "test-4",
                label: "Test 4",
                testNumber: 4,
                correctAnswers: {
                    1: "finance",
                    2: ["maths", "math", "mathematics"],
                    3: "business",
                    4: ["17", "seventeen"],
                    5: ["holiday", "holidays", "vacation", "vacations"],
                    6: "college",
                    7: "location",
                    8: "jeans",
                    9: "late",
                    10: "smile",
                    11: "A",
                    12: "B",
                    13: "A",
                    14: "C",
                    15: "A",
                    16: "B",
                    17: "B",
                    18: "D",
                    19: "A",
                    20: "E",
                    21: "A",
                    22: "A",
                    23: "C",
                    24: "C",
                    25: "B",
                    26: "A",
                    27: ["B", "C"],
                    28: ["B", "C"],
                    29: ["D", "E"],
                    30: ["D", "E"],
                    31: "destruction",
                    32: ["universities", "university"],
                    33: "political",
                    34: ["port", "ports"],
                    35: ["slaves", "slavery"],
                    36: "taxation",
                    37: "sugar",
                    38: "tea",
                    39: "transportation",
                    40: "night",
                },
            },
        ],
    },
    {
        id: "cambridge-12",
        title: "Cambridge IELTS 12",
        examLabel: "Cam 12 Academic",
        cambridgeNumber: 12,
        variant: "academic",
        tests: [
            {
                id: "test-1",
                label: "Test 1",
                testNumber: 1,
                correctAnswers: {
                    1: "mountains",
                    2: "horse",
                    3: ["garden", "gardens"],
                    4: "lunch",
                    5: "map",
                    6: "experience",
                    7: "ratchesons",
                    8: "helmet",
                    9: "shops",
                    10: "267",
                    11: "A",
                    12: "A",
                    13: "C",
                    14: "C",
                    15: ["A", "E"],
                    16: ["A", "E"],
                    17: "F",
                    18: "C",
                    19: "D",
                    20: "B",
                    21: "B",
                    22: "C",
                    23: "C",
                    24: "budget",
                    25: "employment",
                    26: "safety",
                    27: "insurance",
                    28: "diary",
                    29: "database",
                    30: "museum",
                    31: "damage",
                    32: "side effects",
                    33: "bridge",
                    34: "confusion",
                    35: "smartphone",
                    36: "resources",
                    37: ["unnecessary", "not necessary"],
                    38: "chocolate bar",
                    39: "problem",
                    40: "market share",
                },
            },
            {
                id: "test-2",
                label: "Test 2",
                testNumber: 2,
                correctAnswers: {
                    1: "2.45",
                    2: "band",
                    3: "play",
                    4: "scientist",
                    5: "river",
                    6: "grandparents",
                    7: "handsworth",
                    8: "traditional",
                    9: "outdoor",
                    10: "logo",
                    11: "B",
                    12: "C",
                    13: "A",
                    14: "B",
                    15: "C",
                    16: "F",
                    17: "B",
                    18: "E",
                    19: "G",
                    20: "C",
                    21: "C",
                    22: "B",
                    23: "C",
                    24: "A",
                    25: "C",
                    26: "E",
                    27: "G",
                    28: "D",
                    29: "C",
                    30: "A",
                    31: "bullying",
                    32: "superiority",
                    33: "personality",
                    34: "structural",
                    35: "absence",
                    36: "confidence",
                    37: "visions",
                    38: "democratic",
                    39: "respect",
                    40: "mediator",
                },
            },
            {
                id: "test-3",
                label: "Test 3",
                testNumber: 3,
                correctAnswers: {
                    1: ["travel", "travelling", "traveling"],
                    2: "history",
                    3: "study",
                    4: "teenagers",
                    5: "kitchen",
                    6: "crime",
                    7: ["appointment", "booking"],
                    8: "sugar",
                    9: "stamps",
                    10: "parking",
                    11: ["D", "E"],
                    12: ["D", "E"],
                    13: ["A", "C"],
                    14: ["A", "C"],
                    15: "C",
                    16: "B",
                    17: "A",
                    18: "stress",
                    19: "weight",
                    20: "families",
                    21: "C",
                    22: "E",
                    23: "H",
                    24: "B",
                    25: "A",
                    26: "F",
                    27: "A",
                    28: "C",
                    29: "B",
                    30: "B",
                    31: "insects",
                    32: ["behaviour", "behavior"],
                    33: "father",
                    34: ["complex", "complicated"],
                    35: ["reproduction", "breeding"],
                    36: "control",
                    37: ["duck", "ducks"],
                    38: "language",
                    39: "food",
                    40: ["cost", "costs", "price", "prices", "bill", "bills"],
                },
            },
            {
                id: "test-4",
                label: "Test 4",
                testNumber: 4,
                correctAnswers: {
                    1: "temporary",
                    2: "doctor",
                    3: "africa",
                    4: "youth",
                    5: "may",
                    6: "cheese",
                    7: "arbuthnot",
                    8: "dg7 4ph",
                    9: "tuesday",
                    10: ["talk", "presentation"],
                    11: "A",
                    12: "C",
                    13: "B",
                    14: "B",
                    15: "H",
                    16: "C",
                    17: "F",
                    18: "G",
                    19: "I",
                    20: "B",
                    21: "classification",
                    22: "worst",
                    23: "slides",
                    24: "issues",
                    25: "F",
                    26: "A",
                    27: "E",
                    28: "C",
                    29: "G",
                    30: "B",
                    31: ["garden", "gardens"],
                    32: "political",
                    33: ["work", "study"],
                    34: "fountain",
                    35: "social",
                    36: "lively",
                    37: "training",
                    38: "culture",
                    39: "nature",
                    40: "silent",
                },
            },
        ],
    },
    {
        id: "cambridge-11",
        title: "Cambridge IELTS 11",
        examLabel: "Cam 11 Academic",
        cambridgeNumber: 11,
        variant: "academic",
        tests: [
            {
                id: "test-1",
                label: "Test 1",
                testNumber: 1,
                correctAnswers: {
                    1: "charlton",
                    2: ["115", "one hundred fifteen"],
                    3: "cash",
                    4: "parking",
                    5: "music",
                    6: "entry",
                    7: "stage",
                    8: "code",
                    9: ["floor", "floors"],
                    10: ["decoration", "decorations"],
                    11: ["animal", "animals"],
                    12: ["tool", "tools"],
                    13: "shoes",
                    14: ["dog", "dogs"],
                    15: "F",
                    16: "G",
                    17: "D",
                    18: "H",
                    19: "C",
                    20: "A",
                    21: "C",
                    22: "B",
                    23: "B",
                    24: "C",
                    25: "A",
                    26: "B",
                    27: "C",
                    28: "A",
                    29: "B",
                    30: "A",
                    31: "conservation",
                    32: ["food", "foods"],
                    33: "surface",
                    34: ["oxygen", "o2"],
                    35: "mammals",
                    36: "ice",
                    37: ["decline", "declining", "decrease"],
                    38: "map",
                    39: "migration",
                    40: "consumption",
                },
            },
            {
                id: "test-2",
                label: "Test 2",
                testNumber: 2,
                correctAnswers: {
                    1: "hostel",
                    2: "buckleigh",
                    3: "pe9 7qt",
                    4: "waiter",
                    5: "politics",
                    6: "cycling",
                    7: "cinema",
                    8: "disabled",
                    9: ["4.30", "4:30", "half past four"],
                    10: "07788 136711",
                    11: ["A", "B"],
                    12: ["A", "B"],
                    13: ["B", "D"],
                    14: ["B", "D"],
                    15: ["C", "E"],
                    16: ["C", "E"],
                    17: "G",
                    18: "D",
                    19: "B",
                    20: "F",
                    21: "A",
                    22: "A",
                    23: "C",
                    24: "B",
                    25: "B",
                    26: "B",
                    27: ["A", "D"],
                    28: ["A", "D"],
                    29: ["C", "E"],
                    30: ["C", "E"],
                    31: "social",
                    32: "factory",
                    33: "canal",
                    34: "bridge",
                    35: "box",
                    36: "screen",
                    37: "rubber",
                    38: "curved",
                    39: "curtains",
                    40: "international",
                },
            },
            {
                id: "test-3",
                label: "Test 3",
                testNumber: 3,
                correctAnswers: {
                    1: "birds",
                    2: "flowers",
                    3: "mushrooms",
                    4: "river",
                    5: "cave",
                    6: "tiger",
                    7: "dancing",
                    8: "crying",
                    9: "grass",
                    10: "scarf",
                    11: "C",
                    12: "B",
                    13: "B",
                    14: "A",
                    15: "C",
                    16: "G",
                    17: "A",
                    18: "C",
                    19: "B",
                    20: "F",
                    21: "B",
                    22: "A",
                    23: "B",
                    24: "B",
                    25: "A",
                    26: "B",
                    27: "D",
                    28: "A",
                    29: "C",
                    30: "F",
                    31: ["attitude", "attitudes"],
                    32: "numbers",
                    33: ["time", "minutes"],
                    34: "software",
                    35: "patients",
                    36: ["emotions", "feelings"],
                    37: "income",
                    38: "comfortable",
                    39: "observation",
                    40: "analysis",
                },
            },
            {
                id: "test-4",
                label: "Test 4",
                testNumber: 4,
                correctAnswers: {
                    1: "secondary",
                    2: "flute",
                    3: "cinema",
                    4: "concert",
                    5: "market",
                    6: "bythwaite",
                    7: "actor",
                    8: "A",
                    9: "B",
                    10: "C",
                    11: "E",
                    12: "D",
                    13: "G",
                    14: "B",
                    15: "C",
                    16: "A",
                    17: "F",
                    18: "H",
                    19: "C",
                    20: "B",
                    21: ["B", "D"],
                    22: ["B", "D"],
                    23: ["A", "B"],
                    24: ["A", "B"],
                    25: ["B", "E"],
                    26: ["B", "E"],
                    27: "C",
                    28: "A",
                    29: "A",
                    30: "C",
                    31: "dry",
                    32: "hard",
                    33: ["sugar", "sugars"],
                    34: "roots",
                    35: ["moist", "damp", "wet"],
                    36: "variety",
                    37: "cattle",
                    38: ["gardens", "gardening"],
                    39: "grasses",
                    40: ["payment", "payments", "money"],
                },
            },
        ],
    },
    {
        id: "cambridge-10",
        title: "Cambridge IELTS 10",
        examLabel: "Cam 10 Academic",
        cambridgeNumber: 10,
        variant: "academic",
        tests: [
            {
                id: "test-1",
                label: "Test 1",
                testNumber: 1,
                correctAnswers: {
                    1: "ardleigh",
                    2: "newspaper",
                    3: "theme",
                    4: "tent",
                    5: "castle",
                    6: ["beach", "beaches"],
                    7: "2020",
                    8: "flight",
                    9: "429",
                    10: "dinner",
                    11: ["A", "C"],
                    12: ["A", "C"],
                    13: "health problems",
                    14: "safety rules",
                    15: "plan",
                    16: "joining",
                    17: "free entry",
                    18: "peak",
                    19: "guests",
                    20: ["photo card", "photo cards"],
                    21: "C",
                    22: "A",
                    23: "B",
                    24: "A",
                    25: "C",
                    26: "presentation",
                    27: "model",
                    28: ["material", "materials"],
                    29: "grant",
                    30: "technical",
                    31: "gene",
                    32: ["power", "powers"],
                    33: "strangers",
                    34: "erosion",
                    35: "islands",
                    36: "roads",
                    37: "fishing",
                    38: "reproduction",
                    39: ["method", "methods"],
                    40: "expansion",
                },
            },
            {
                id: "test-2",
                label: "Test 2",
                testNumber: 2,
                correctAnswers: {
                    1: "hardie",
                    2: "19",
                    3: "gt8 2lc",
                    4: "hairdresser",
                    5: ["dentist", "dentist's"],
                    6: "lighting",
                    7: "trains",
                    8: "safe",
                    9: "shower",
                    10: "training",
                    11: "A",
                    12: "C",
                    13: "C",
                    14: "A",
                    15: "E",
                    16: "F",
                    17: "D",
                    18: "H",
                    19: "A",
                    20: "B",
                    21: ["B", "C"],
                    22: ["B", "C"],
                    23: ["B", "E"],
                    24: ["B", "E"],
                    25: "A",
                    26: "C",
                    27: "C",
                    28: "A",
                    29: "B",
                    30: "A",
                    31: "competition",
                    32: "global",
                    33: "demand",
                    34: "customers",
                    35: "regulation",
                    36: "project",
                    37: "flexible",
                    38: "leadership",
                    39: "women",
                    40: "self-employed",
                },
            },
            {
                id: "test-3",
                label: "Test 3",
                testNumber: 3,
                correctAnswers: {
                    1: "4",
                    2: "46 wombat",
                    3: "thursday",
                    4: ["8.30", "8:30"],
                    5: "red",
                    6: "lunch",
                    7: "glasses",
                    8: "ball",
                    9: "aunt",
                    10: "month",
                    11: ["C", "E"],
                    12: ["C", "E"],
                    13: "B",
                    14: "A",
                    15: "C",
                    16: "B",
                    17: "C",
                    18: "D",
                    19: "D",
                    20: "A",
                    21: "C",
                    22: "A",
                    23: "A",
                    24: "B",
                    25: "B",
                    26: "E",
                    27: "D",
                    28: "A",
                    29: "G",
                    30: "C",
                    31: ["achievement", "achievements"],
                    32: ["personality", "character"],
                    33: "situational",
                    34: "friend",
                    35: ["aspirations", "ambitions"],
                    36: "style",
                    37: "development",
                    38: "vision",
                    39: "structures",
                    40: ["innovation", "innovations"],
                },
            },
            {
                id: "test-4",
                label: "Test 4",
                testNumber: 4,
                correctAnswers: {
                    1: "pargetter",
                    2: "east",
                    3: "library",
                    4: ["morning", "mornings"],
                    5: "postbox",
                    6: "prices",
                    7: "glass",
                    8: "cooker",
                    9: "week",
                    10: "fence",
                    11: "B",
                    12: "B",
                    13: "A",
                    14: "A",
                    15: "C",
                    16: "trains",
                    17: "dark",
                    18: "games",
                    19: "guided tour",
                    20: ["ladder", "ladders"],
                    21: ["A", "E"],
                    22: ["A", "E"],
                    23: ["B", "C"],
                    24: ["B", "C"],
                    25: "D",
                    26: "F",
                    27: "G",
                    28: "B",
                    29: "E",
                    30: "C",
                    31: "C",
                    32: "B",
                    33: "C",
                    34: ["metal", "metals"],
                    35: "space",
                    36: "memory",
                    37: "solar",
                    38: "oil",
                    39: "waste",
                    40: "tests",
                },
            },
        ],
    },
];
export function getListeningSet(setId: string): ListeningSet | undefined {
    return listeningSets.find((s) => s.id === setId);
}
export function getListeningTest(setId: string, testId: string): (ListeningTest & {
    set: ListeningSet;
}) | undefined {
    const set = getListeningSet(setId);
    if (!set)
        return undefined;
    const test = set.tests.find((t) => t.id === testId);
    if (!test)
        return undefined;
    return { ...test, set };
}
const AUDIO_BASE_URL = "https://pub-07cb27fc21e14030b9a45e98dc04b6ee.r2.dev";
export function getAllAudios(): {
    book: number;
    test: number;
    part: number;
    url: string;
}[] {
    const audios: {
        book: number;
        test: number;
        part: number;
        url: string;
    }[] = [];
    const base = AUDIO_BASE_URL.replace(/\/$/, "");
    for (let book = 11; book <= 20; book++) {
        for (let test = 1; test <= 4; test++) {
            for (let part = 1; part <= 4; part++) {
                audios.push({
                    book,
                    test,
                    part,
                    url: base
                        ? `${base}/cambridge-${book}/test-${test}/part-${part}.mp3`
                        : `/${path(book, test, part)}`,
                });
            }
        }
    }
    return audios;
}
function path(book: number, test: number, part: number): string {
    return `audios/cambridge-${book}/test-${test}/part-${part}.mp3`;
}

export function getListeningAudioUrls(set: ListeningSet, test: ListeningTest, part: number): string[] {
    const book = set.cambridgeNumber;
    const t = test.testNumber;
    const seen = new Set<string>();
    const out: string[] = [];
    if (AUDIO_BASE_URL) {
        const base = AUDIO_BASE_URL.replace(/\/$/, "");
        const primary = `${base}/cambridge-${book}/test-${t}/part-${part}.mp3`;
        seen.add(primary);
        out.push(primary);
    }
    else {
        const local = `/${path(book, t, part)}`;
        seen.add(local);
        out.push(local);
    }
    for (const u of engnovateListeningAudioCandidates(book, t, part)) {
        if (!seen.has(u)) {
            seen.add(u);
            out.push(u);
        }
    }
    return out;
}
